name: OnigoPlugin
version: ${project.version}
main: net.kigawa.onigoplugin.OnigoPlugin
api-version: 1.16
authors: [ kigawa ]
softdepend: [UtilPlugin]
commands:
  onigo:
    description: for onigo
    usage: /onigo <subcommand>
    permission: onigoplugin.onigo
  test:
    description: for test
    usage: /test
    permission: onigoplugin.test
  onigocreate:
    description: create onigp game
    usage: /createonigo <subcommand>
    permission: onigoplugin.createonigo
  stage:
    description: for stage
    usage: /stage <subcommand>
    permission: onigoplugin.stage